name: Deploy

on:
    push:
        branches:
            - main
permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   uses: oven-sh/setup-bun@v2
            -   run: bun install

            -   name: Build
                run: bun run build

            -   name: Deploy
                uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: .vitepress/dist
